name: Maven Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: byteandbit-release # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup maven
      run: |
        sed -i 's/123name/'"$MAVEN_USERNAME"'/g' settings.xml
        sed -i 's/123password/'"$MAVEN_PASSWORD"'/g' settings.xml
      
    - name: Build with Maven
      run: mvn clean package javadoc:javadoc deploy -s s $GITHUB_WORKSPACE/settings.xml
